### ISSUE TITLE
Installed plugin manifest is incorrect

### ISSUE THREAD

**Issue by samhowes** [BU-NU-CLOUD-SP16/Automated-Release-Notes#23]
Plugin Name appears as ARNServerPlugin. I would expect it to be Automated Release Notes

Plugin Link goes to jetbrains.com
![image](https://cloud.githubusercontent.com/assets/6216665/14769559/649e45c4-0a29-11e6-97a1-271d76cd9d0d.png)

**Comment by hiteshlaware** [comment]
changed name to automated release notes

**Comment by samhowes** [comment]
Please provide a screenshot

**Comment by hiteshlaware** [comment]
![pluginname](https://cloud.githubusercontent.com/assets/14117843/14772063/7494d89c-0a67-11e6-9d27-1c1ece74fa10.png)

**Comment by samhowes** [comment]
Looks good
