### ISSUE TITLE
The instructions for Building say to download as Zip

### ISSUE THREAD

**Issue by samhowes** [BU-NU-CLOUD-SP16/Automated-Release-Notes#25]
This is non-standard for github projects. Instead I would expect a code snippet like `git clone <url>` that can be copy and pasted into the command line.

See: [FlowJS](https://github.com/flowjs/flow.js#how-can-i-install-it) for an example

**Comment by hiteshlaware** [comment]
done

**Comment by samhowes** [comment]
Looks good
