### ISSUE TITLE
Last bulleted item in Build steps is Platform specific

### ISSUE THREAD

**Issue by samhowes** [BU-NU-CLOUD-SP16/Automated-Release-Notes#26]
The instruction says to restart TeamCity from Local Services. This method of restarting TeamCity is only used when TeamCity is installed on a windows machine, and when it is installed as a windows service. Since TeamCity can be installed on any platform, this goes against best practice. 

It is best to simply say restart teamcity server. If desired, a link to the TeamCity documentation can be made for better instructions.

**Comment by karuneshmahajan** [comment]
Corrected the build step where it mentions to restart teamcity server to make it more platform independent.

**Comment by samhowes** [comment]
Looks good
