### ISSUE TITLE
Configuration Steps: "File path relative to checkout directory" is not specific enough, should be named "Output file"

### ISSUE THREAD

**Issue by samhowes** [BU-NU-CLOUD-SP16/Automated-Release-Notes#27]
A comment below the box can be used to indicate that the path should be relative to the checkout directory as with the default settings of Runner Type, Step name, and execute step.

**Comment by karuneshmahajan** [comment]
"File path relative to the checkout directory" updated to "Output File Path" and also added a small note saying "Path should be relative to the checkout directory"

![image](https://cloud.githubusercontent.com/assets/14364768/14773833/f6e7b782-0a7c-11e6-8194-3783ab839b65.png)

**Comment by samhowes** [comment]
Looks good.
