### ISSUE TITLE
Runner type in Build Step configuration should be listed as "Automated Release Notes"

### ISSUE THREAD

**Issue by samhowes** [BU-NU-CLOUD-SP16/Automated-Release-Notes#28]
Currently listed as ARNRunner

**Comment by karuneshmahajan** [comment]
The runner type name in build step has been updated to "Automated Release Notes"

![image](https://cloud.githubusercontent.com/assets/14364768/14771884/a97312b6-0a64-11e6-972f-ba876d10621b.png)

**Comment by SamuelHowes-ma** [comment]
Looks good
