### ISSUE TITLE
Description of File Path in Readme is incorrect

### ISSUE THREAD

**Issue by samhowes** [BU-NU-CLOUD-SP16/Automated-Release-Notes#29]
The readme states: 

> For 'File Path relative to Checkout Directory' choose a Folder name where you want the release notes to be generated.This file will be generated in **TeamCity\buildAgent\work\** once you run the build successfully.

Which is incorrect. The file will be generated in <build_agent_home>\work<identifier>, which is in fact the checkout directory. Instead of listing the file path, yourself, you should instead say: 

This file will be generated relative to the [checkout directory](https://confluence.jetbrains.com/display/TCD9/Build+Checkout+Directory). (Note the link to TeamCity documentation) Whenever you can, refer to TeamCity's documentation instead of your own.

**Comment by karuneshmahajan** [comment]
Description of output file path in readme file corrected.

**Comment by SamuelHowes-ma** [comment]
Looks good.
