### ISSUE TITLE
Format String is Optional, but the UI does not indicate that it is optional

### ISSUE THREAD

**Issue by samhowes** [BU-NU-CLOUD-SP16/Automated-Release-Notes#30]
If a parameter is optional, it should be shown as such:

Format String (optional):

**Comment by samhowes** [comment]
The most ideal approach would be to have that field populated with the default format string. The best form of documentation is examples. If you provide the user with the default format string, that makes it pretty easy to customize it, instead of trying to figure it out from scratch

**Comment by karuneshmahajan** [comment]
Default format string provided in the text area.

![image](https://cloud.githubusercontent.com/assets/14364768/14773804/86684f8a-0a7c-11e6-9a58-06593bc5fa7d.png)

**Comment by SamuelHowes-ma** [comment]
Great!
