### ISSUE TITLE
VSTS Url needs clarifying

### ISSUE THREAD

**Issue by SamuelHowes-ma** [BU-NU-CLOUD-SP16/Automated-Release-Notes#33]
Give a hint to the user about what URL to actually enter here. Does it have to be the url to the base of a specific project? Does it need to be a sub-url?

**Comment by JayJian** [comment]
I think it would be the url of the entrance of a project on VSTS directly, instead of a sub-url.

**Comment by samhowes** [comment]
This should be clarified explicitly in the UI.

**Comment by seshank4** [comment]
![image](https://cloud.githubusercontent.com/assets/14364741/14809877/02f84af0-0b5e-11e6-81dd-ba049eeb650e.png)

**Comment by seshank4** [comment]
![image](https://cloud.githubusercontent.com/assets/14364741/14810003/b11618e2-0b5e-11e6-9631-2ceb66da2bd8.png)
