### ISSUE TITLE
Output File Path does not do what is expected

### ISSUE THREAD

**Issue by samhowes** [BU-NU-CLOUD-SP16/Automated-Release-Notes#34]
In the UI I entered "ReleaseNotes" for the Output File Path
![image](https://cloud.githubusercontent.com/assets/6216665/14795145/20a12c52-0af5-11e6-8f5b-524d31823900.png)

I then selected "Text" as the output format. Given these two inputs, I expected that a single file would be output at the root of the checkout directory with the name "ReleaseNotes.txt", and If I had checked pdf, I would expect a file at the same place in the checkout directory with the name "ReleaseNotes.pdf".

Instead a folder was created with that name, and a file was placed inside: 
![image](https://cloud.githubusercontent.com/assets/6216665/14795212/6f9f58c4-0af5-11e6-88f4-c9fb55ecfb54.png)

The UI does not indicate to the user that this is what the output will be. This should be fixed by either:
1. Update the UI to be more explanatory
2. Name the file what the user entered in the box, and append the correct extension to it. I.e. "ReleasNotes" yields the output filename: "ReleaseNotes.txt". 

My preference is number 2.

**Comment by seshank4** [comment]
If we follow number 2 then there might be a problem when more than one build is running with the same build configuration. The file will get overwritten because it will always be generated with the name entered in the build configuration. With the current approach the file name generated is always unique for each build.

I would suggest changing the UI to say Output folder name, would that work?

**Comment by samhowes** [comment]
Good though. However, a build agent will only execute one build at a time. Since this file is in the Agent's [checkout directory](https://confluence.jetbrains.com/display/TCD9/Build+Checkout+Directory) 

> The build checkout directory is a directory on the **TeamCity agent machine**

Yes, Multiple builds can run at the same time, but only if you have multiple build agents. When you install multiple build agents, each agent has its own directory. We have 3 agents set up, here is the directory structure: 
![image](https://cloud.githubusercontent.com/assets/6216665/14797596/8a225a96-0b01-11e6-9227-1f05da80a2c8.png)

Each "Localx" folder is an agent. Note that each agent folder contains a "work" directory. This way, no files will conflict. Number 2 should work just fine.

The server directory contains the "data" directory, as well as "Install" which is TeamCityHome.

**Comment by seshank4** [comment]
![image](https://cloud.githubusercontent.com/assets/14364741/14810098/26bd26c6-0b5f-11e6-87af-b8dc1315d251.png)

![image](https://cloud.githubusercontent.com/assets/14364741/14810142/5a3348f0-0b5f-11e6-9517-22e5188dc07b.png)

**Comment by seshank4** [comment]
Made the required changes
